import { CONTRACT_VERSION, type ClinicalReview } from "../shared/contracts/common.js";
import { CasePackSchema } from "../shared/contracts/server.js";

const clinicalReview: ClinicalReview = {
  sourceTitle: "Resuscitation Council UK: The ABCDE Approach",
  sourceUrl: "https://www.resus.org.uk/library/abcde-approach",
  sourceRevision: "Published October 2015; reviewed May 2021; updated July 2024",
  sourceApplicability: "clinical_source",
  reviewStatus: "draft_unreviewed",
};

const developmentFixtureReview: ClinicalReview = {
  sourceTitle: "DO NO HARM product specification: authored scenario rules",
  sourcePath: "specs.md#3-authored-scenario-and-progression",
  sourceRevision: "Updated 13 September 2026",
  sourceApplicability: "local_development_fixture",
  reviewStatus: "draft_unreviewed",
};

const equipment = [
  ["heart_monitor", "Bedside heart monitor", "heart_monitor", ["attach ECG leads", "attach SpO2 probe", "apply BP cuff", "measure BP"]],
  ["oxygen_station", "Wall oxygen station", "oxygen_station", ["select device", "set flow", "apply", "adjust", "stop"]],
  ["iv_station", "IV station", "iv_station", ["establish access", "inspect patency"]],
  ["ecg_machine", "12-lead ECG machine", "ecg_machine", ["request", "acquire", "open", "interpret"]],
  ["medication_trolley", "Medication trolley", "medication_trolley", ["inspect chart", "prepare medication", "review order", "administer"]],
  ["results_workstation", "Results workstation", "results_workstation", ["request blood tests", "inspect results"]],
  ["clipboard", "Clinical clipboard", "clipboard", ["save note", "revise note"]],
  ["call_station", "Senior call station", "call_station", ["request review", "give handoff"]],
  ["suction", "Wall suction", "suction", []],
] as const;

export const chestPainCaseV1 = CasePackSchema.parse({
  contractVersion: CONTRACT_VERSION,
  caseId: "adult_chest_pain",
  caseVersion: "1.0.0-draft.2",
  title: "Chest pain with evolving instability",
  educationalUse: "formative_simulation_only",
  clinicalReview,
  patient: {
    id: "patient_morgan_lee",
    displayName: "Morgan Lee",
    fictional: true,
    ageYears: 58,
    weightKg: 82,
    presentingComplaint: "Central chest pressure",
    symptomOnset: "At rest, approximately 45 minutes before arrival",
    painDescription: "Heavy central pressure radiating to the left arm, currently 8/10",
    allergies: ["No known drug allergies reported"],
    currentMedications: ["Amlodipine 5 mg once daily"],
    comorbidities: ["Hypertension", "Current tobacco use"],
  },
  opening: "I have a heavy pressure in the middle of my chest and I feel clammy.",
  observations: [
    {
      contractVersion: CONTRACT_VERSION,
      id: "general_appearance",
      label: "General appearance",
      kind: "examination",
      value: "Alert, anxious, pale and clammy",
      observableBy: "initial",
      studentVisible: true,
      availableAtSimulationMs: 0,
      clinicalReview,
    },
    {
      contractVersion: CONTRACT_VERSION,
      id: "pain_score",
      label: "Pain score",
      kind: "symptom",
      value: 8,
      unit: "/10",
      observableBy: "history",
      studentVisible: true,
      availableAtSimulationMs: 0,
      clinicalReview,
    },
    {
      contractVersion: CONTRACT_VERSION,
      id: "heart_rate",
      label: "Heart rate",
      kind: "vital",
      value: 104,
      unit: "beats/min",
      observableBy: "device",
      studentVisible: true,
      availableAtSimulationMs: 0,
      clinicalReview,
    },
    {
      contractVersion: CONTRACT_VERSION,
      id: "spo2",
      label: "Oxygen saturation on room air",
      kind: "vital",
      value: 96,
      unit: "%",
      observableBy: "device",
      studentVisible: true,
      availableAtSimulationMs: 0,
      clinicalReview,
    },
    {
      contractVersion: CONTRACT_VERSION,
      id: "respiratory_rate",
      label: "Respiratory rate",
      kind: "vital",
      value: 20,
      unit: "breaths/min",
      observableBy: "assessment",
      studentVisible: true,
      availableAtSimulationMs: 0,
      clinicalReview,
    },
    {
      contractVersion: CONTRACT_VERSION,
      id: "blood_pressure",
      label: "Blood pressure",
      kind: "vital",
      value: "146/88",
      unit: "mmHg",
      observableBy: "device",
      studentVisible: true,
      availableAtSimulationMs: 0,
      clinicalReview,
    },
    {
      contractVersion: CONTRACT_VERSION,
      id: "twelve_lead_ecg",
      label: "12-lead ECG",
      kind: "investigation",
      value: "Draft finding withheld pending specialist ECG review",
      observableBy: "result",
      studentVisible: false,
      availableAtSimulationMs: 120000,
      clinicalReview,
    },
  ],
  equipment: equipment.map(([id, label, kind, supportedActions]) => ({
    contractVersion: CONTRACT_VERSION,
    id,
    label,
    kind,
    availability: id === "suction" ? "visible_unavailable" : "available",
    supportedActions: [...supportedActions],
  })),
  medicationRules: [
    {
      contractVersion: CONTRACT_VERSION,
      id: "aspirin_300mg_tablet",
      name: "Aspirin",
      formulation: "300 mg dispersible tablet",
      concentration: "300 mg per tablet",
      allowedUnits: ["mg", "g"],
      allowedRoutes: ["oral"],
      patientInformation: "Check identity, allergy history, contraindications and prior doses before preparing.",
      referenceDoseRule: "300 mg orally, crushed or chewed, as soon as possible for suspected ACS",
      doseRule: { quantity: 300, unit: "mg" },
      contraindications: [
        "Known aspirin hypersensitivity",
        "Active major bleeding",
        "Aspirin already administered for this presentation",
      ],
      requiredObservations: ["allergy history", "medication administration history"],
      requiredAccess: [],
      authorizationRule: "student_permitted",
      repeatIntervalMs: null,
      cumulativeLimit: { quantity: 300, unit: "mg" },
      onsetMs: 60000,
      durationMs: null,
      effectRule: "At 60 seconds, record the authored antiplatelet action as active; do not change heart rate, blood pressure, pain score, or oxygen saturation",
      reassessmentRequirement: "Continue ABCDE reassessment and seek urgent senior review",
      inappropriateAttemptRules: [
        { condition: "dose is not exactly 300 mg", outcome: "block", rationale: "Outside the single reviewed draft dose" },
        { condition: "route is not oral", outcome: "block", rationale: "Unsupported route for this case formulation" },
        { condition: "aspirin already administered", outcome: "block", rationale: "Prevents an unintended duplicate dose" },
      ],
      clinicalReview,
    },
  ],
  fluidRules: [
    {
      contractVersion: CONTRACT_VERSION,
      id: "sodium_chloride_0_9",
      name: "Sodium chloride 0.9% development fixture",
      allowedVolumeUnits: ["mL", "L"],
      allowedRateUnits: ["mL/h", "L/h"],
      maximumVolumeMl: 500,
      maximumRateMlPerHour: 1000,
      requiredAccess: "iv",
      authorizationRule: "student_permitted",
      effectRule:
        "Account for delivered volume only; this unreviewed development fixture has no physiological effect.",
      clinicalReview: developmentFixtureReview,
    },
  ],
  scenarioRules: {
    baseline: {
      heartRate: 104,
      spo2: 96,
      respiratoryRate: 20,
      systolicBp: 146,
      diastolicBp: 88,
      painScore: 8,
      presentation: "Alert, anxious, pale and clammy",
    },
    timelyCare: {
      entersBeforeMs: 120000,
      timeoutAfterMs: 180000,
      entryCondition:
        "An accepted aspirin administration occurs before delayed-care entry.",
      exitCondition:
        "The authored aspirin effect is recorded and senior review is acknowledged.",
      timeoutBehavior:
        "Close the branch as timed out without inventing a further clinical consequence.",
    },
    delayedCare: {
      entersAtMs: 120000,
      timesOutAtMs: 300000,
      observations: {
        heartRate: 118,
        spo2: 93,
        respiratoryRate: 24,
        systolicBp: 112,
        diastolicBp: 72,
        painScore: 9,
        presentation: "More distressed, pale and clammy",
      },
      entryCondition:
        "Simulation reaches 120 seconds without an accepted aspirin administration.",
      exitCondition:
        "Aspirin is accepted and senior review is acknowledged.",
      timeoutBehavior:
        "Close the branch as timed out at 300 seconds and retain the last authored observations.",
    },
    inappropriateAttempt: {
      timeoutAfterMs: 60000,
      entryCondition:
        "A syntactically valid medication command is blocked by an authored medication rule.",
      exitCondition:
        "A valid medication administration is accepted.",
      timeoutBehavior:
        "Return to arrival, or enter delayed care when its time condition has been reached.",
    },
    seniorAcknowledgementDelayMs: 15000,
    clinicalReview: developmentFixtureReview,
  },
  hiddenRubric: {
    contractVersion: CONTRACT_VERSION,
    rubricVersion: "1.0.0-draft.2",
    criteria: [
      {
        id: "assessment",
        expectedEvidence: ["Focused chest-pain history", "ABCDE observations", "monitoring established"],
        needsWorkIndicators: ["No reassessment of an abnormal observation"],
      },
      {
        id: "interpretation",
        expectedEvidence: ["12-lead ECG opened", "Student interpretation recorded"],
        needsWorkIndicators: ["Finding viewed without an interpretation"],
      },
      {
        id: "intervention_selection_dosing",
        expectedEvidence: ["Medication parameters checked", "Administration receipt present"],
        needsWorkIndicators: ["Prepared order described as administered"],
      },
      {
        id: "reassessment",
        expectedEvidence: ["Pain and observations reassessed after intervention"],
        needsWorkIndicators: ["No post-intervention reassessment"],
      },
      {
        id: "escalation",
        expectedEvidence: ["Senior review requested", "Acknowledgment received"],
        needsWorkIndicators: ["Handoff without an escalation request"],
      },
      {
        id: "communication_documentation",
        expectedEvidence: ["Working diagnosis and plan saved", "Structured handoff recorded"],
        needsWorkIndicators: ["Handoff claim conflicts with administration evidence"],
      },
    ],
  },
  unresolvedClinicalParameters: [
    "Name and revision of the local acute-coronary-syndrome protocol",
    "Final diagnosis and complete time-dependent physiology for timely and delayed branches",
    "Specialist-reviewed 12-lead ECG finding and calibrated artwork",
    "Acceptable alternative assessment and treatment sequences",
    "Aspirin contraindication wording, administration prerequisites, and case-specific exception rules",
    "Whether a nitrate or analgesic is included; if included, its dosing, routes, contraindications, repeat limits, and effects",
    "Reviewed oxygen-device settings and thresholds for this patient",
    "Reviewed IV-fluid availability, settings, contraindications, and effects",
    "Deterioration timing, observation changes, exit conditions, and timeout behavior",
    "Aspirin's 60-second engine effect marker (which intentionally makes no vital-sign change)",
    "Development IV-fluid limits and the decision to apply no physiological response",
    "Reviewer identity and signed review date for the complete case and hidden rubric",
  ],
});
